import { FiLock } from 'react-icons/fi'
import './LegalPage.css'

function PrivacyPolicy() {
  return (
    <div className="legal-page">
      <div className="page-container">
        <div className="legal-header">
          <h1>
            <FiLock /> Privacy Policy
          </h1>
          <p className="last-updated">Last Updated: 15-Dec-2025</p>
        </div>

        <div className="legal-content">
          <p className="intro">
            ApexNeural Private Limited ("ApexNeural", "we", "us", "our") respects your privacy and is committed to protecting your personal data. This Privacy Policy describes how we collect, use, store, share, and protect your information in accordance with the Digital Personal Data Protection Act, 2023 (DPDP Act), the Information Technology Act, 2000, the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 (SPDI Rules), and other applicable laws.
          </p>

          <p className="intro">
            This Privacy Policy applies to your use of this website, its related domains, subdomains, product-specific websites, mobile applications, APIs, dashboards, and any related services operated by ApexNeural (collectively, the "Platform" or "Services").
          </p>

          <p className="intro">
            This website and all related product websites, domains, and subdomains are owned and operated by ApexNeural Private Limited, unless explicitly stated otherwise.
          </p>

          <section>
            <h2>1. Personal Data We Collect</h2>
            
            <h3>1.1 Data Provided by You</h3>
            <p>When you use our Platform, you may voluntarily provide:</p>
            <ul>
              <li>Full name, email address, phone number, and company name</li>
              <li>Login or account registration details</li>
              <li>Billing and payment information (if you purchase paid plans)</li>
              <li>Files, text, source code, documents, datasets, repository links, and other content submitted to run analysis and/or E2E testing workflows ("User Content")</li>
            </ul>

            <h3>1.2 Data Collected Automatically</h3>
            <p>We automatically collect:</p>
            <ul>
              <li>IP address, device and browser type, operating system</li>
              <li>Usage metrics such as pages visited, actions performed, features used, and session duration</li>
              <li>Diagnostic and security logs (for example, error logs and audit logs)</li>
            </ul>

            <h3>1.3 Data Generated by the Services</h3>
            <p>When you run workflows, the Platform may generate and store:</p>
            <ul>
              <li>Analysis results, test outputs, reports, and artifacts</li>
              <li>Workflow execution logs and metadata</li>
            </ul>
          </section>

          <section>
            <h2>2. How We Use Your Personal Data</h2>
            <p>We use your personal data to:</p>
            <ul>
              <li>Provide, operate, and maintain the Platform and Services</li>
              <li>Process your requests, transactions, and workflow executions</li>
              <li>Send you service-related communications (for example, account notifications, workflow status updates)</li>
              <li>Respond to your inquiries and provide customer support</li>
              <li>Improve, personalize, and enhance the Platform</li>
              <li>Detect, prevent, and address security issues, fraud, or abuse</li>
              <li>Comply with legal obligations and enforce our Terms of Use</li>
            </ul>
          </section>

          <section>
            <h2>3. Legal Basis for Processing</h2>
            <p>We process your personal data based on:</p>
            <ul>
              <li>Your consent (where required by law)</li>
              <li>Performance of a contract (to provide the Services you requested)</li>
              <li>Legitimate interests (for example, security, fraud prevention, service improvement)</li>
              <li>Compliance with legal obligations</li>
            </ul>
          </section>

          <section>
            <h2>4. Data Sharing and Disclosure</h2>
            <p>We do not sell your personal data. We may share your data only in the following circumstances:</p>
            <ul>
              <li>With service providers and vendors who assist us in operating the Platform (under strict confidentiality obligations)</li>
              <li>If required by law, court order, or government regulation</li>
              <li>To protect our rights, property, or safety, or that of our users</li>
              <li>In connection with a business transfer (merger, acquisition, etc.)</li>
            </ul>
          </section>

          <section>
            <h2>5. Data Retention</h2>
            <p>We retain your personal data for as long as necessary to provide the Services, comply with legal obligations, resolve disputes, and enforce our agreements. You may request deletion of your account and associated data, subject to applicable legal requirements.</p>
          </section>

          <section>
            <h2>6. Your Rights</h2>
            <p>Under applicable data protection laws (including the DPDP Act), you may have the right to:</p>
            <ul>
              <li>Access and receive a copy of your personal data</li>
              <li>Correct inaccurate or incomplete data</li>
              <li>Request deletion of your personal data</li>
              <li>Withdraw consent (where processing is based on consent)</li>
              <li>Object to certain processing activities</li>
              <li>Data portability (receive your data in a structured format)</li>
            </ul>
            <p>To exercise these rights, please contact us at privacy@apexneural.com.</p>
          </section>

          <section>
            <h2>7. Data Security</h2>
            <p>We implement reasonable technical and organizational measures to protect your personal data against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the internet or electronic storage is 100% secure.</p>
          </section>

          <section>
            <h2>8. International Data Transfers</h2>
            <p>Your data may be processed and stored in servers located outside India. We ensure appropriate safeguards are in place to protect your data in accordance with applicable laws.</p>
          </section>

          <section>
            <h2>9. Children's Privacy</h2>
            <p>The Platform is not intended for individuals under the age of 18. We do not knowingly collect personal data from children.</p>
          </section>

          <section>
            <h2>10. Changes to This Privacy Policy</h2>
            <p>We may update this Privacy Policy from time to time. We will notify you of material changes by posting the updated policy on the Platform and updating the "Last Updated" date.</p>
          </section>

          <section>
            <h2>11. Contact Us</h2>
            <p>If you have questions about this Privacy Policy or wish to exercise your rights, please contact us at:</p>
            <p>
              <strong>Email:</strong> privacy@apexneural.com<br />
              <strong>Address:</strong> ApexNeural Private Limited
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}

export default PrivacyPolicy

